ENV['COCOAPODS_DISABLE_STATS'] = 'true'

platform :ios, '10.0'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

abstract_target 'All' do
  pod 'nntool-shared-swift', :path => '../nntool-shared-swift'

  pod 'CocoaAsyncSocket', '~> 7.6.3'
  pod 'Alamofire', '~> 4.8.2'
  pod 'WKWebViewWithURLProtocol', '~> 0.1.0'

  target 'QoSKit_iOS' do

  end

  target 'QoSKitUnitTests' do
    pod 'Nimble', '~> 8.0.1'
  end
end

