spring:
  profiles:
    active: dev

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false

  couchdb:
    connection:
      url: http://localhost:5984
      #username:
      #password:
    databases:
      - name: measurement
        create-if-not-exists: true
        entities:
          - Measurement
          - MeasurementAgent
      - name: settings
        create-if-not-exists: true
        entities:
          - Settings
          - MeasurementServer
          - QoSMeasurementObjective

server:
  port: 8080

logging:
  level:
    at.alladin.nettest: DEBUG