== IAS server module

=== Building

==== Prerequisites

Linux (any Version)

- make
- cmake
- g++
- liblog4cpp5-dev
- libssl-dev
- libtool
- automake

For a Debian based Linux run the following command as root:

[source,bash]
----
apt install build-essential make cmake automake g++ libtool liblog4cpp5-dev libssl-dev
----

==== Build

With fullfilled prerequisites perform the following steps:

1. Compile ias-server

[source,bash]
----
cd <nntool_eu_directory>/ias-server
mkdir build
cd build
cmake .. # add -DCMAKE_BUILD_TYPE="DEBUG" for debug build
make
----

2. Create dir `/etc/ias-server/`
3. Copy trace.ini to `/etc/ias-server/`
4. Customize and copy `config.json` to `/etc/ias-server/`
5. Create dir `/var/log/ias-server/`

=== Execution
Run `build/ias-server`. Add the `-d` option for daemon mode.

For the usage of TLS-Secured connections, perform the following steps:

1. Create dir `/var/opt/ias-server/certs/{my_fqdn}/`
2. Deploy Certificate with filename `{my_fqdn}.crt` to the folder created in step 1.
3. Deploy Private Key with filename `{my_fqdn}.key` to the folder created in step 1.
4. State the TLS port to be used in `config.json`
5. Restart `ias-server`

=== Docker container

[source,bash]
----
cd <nntool_eu_directory>
docker build -f ias-server.Dockerfile -t nntool.eu/ias-server . 
docker run --rm -it -p 20080:80 -p 20443:443 -p 28080:8080 nntool.eu/ias-server
----
