ENV['COCOAPODS_DISABLE_STATS'] = 'true'

platform :ios, '10.0'

use_frameworks!
inhibit_all_warnings!

abstract_target 'All' do
  pod 'SwiftGen', '~> 6.1.0'
  pod 'SwiftLint', '~> 0.31.0'
  pod 'BartyCrouch', '~> 3.13.0'

  pod 'WebBrowser', '~> 0.1.4'
  
  target 'ios-app' do

  end
end
