[[ias-ios-demo]]
= IAS iOS

.License
----
ias-ios is released under the AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.txt>

Copyright (C) 2016-2020 zafaco GmbH

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License version 3 
as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
----

== Building

=== Prerequisites
* XCode == 11 (see below)
* cocoapods
* NativeScript-cli = 7.x (This is the CLI, NOT the runtime - see below)
* macOS (any Version)

Please Note: The `speed` framework of `ias-ios` uses the `TNSRuntime` (which is part of `nativescript`) provided by `ias-mobile`. NativeScript 7 defaults to the `v8 iOS engine`, which does not include `TNSRuntime`, and is therefore NOT compatible with `speed`. Hence, `tns-ios 6.5.3` must be used for the time being. Moreover, if compiled with xcode 12, the execution of JavaSript code within the `TNSRuntime` fails. Hence, xcode 11 must be used for the time being to compile the `speed` framework of `ias-ios`.

References:

https://nativescript.org/blog/nativescript-7-announcement/

https://github.com/NativeScript/NativeScript/issues/8867

https://github.com/NativeScript/NativeScript/issues/8741

=== Build
With fullfilled prerequisites perform the following steps:

1. Build `ias`, see instructions in `ias/README.md`
2. In directory `qos-client-swift` run `pod install` to install MeasurementKit 
3. In directory `ias-ios`, run `pod install` to install required cocoapods dependencies
4. Open `ias_ios.xcworkspace` in XCode and build target `Demo`

=== Demo Parameters

Modify `Demo/SpeedViewController.m` according to Code-Documentation to edit measurement parameters before `Build`

=== Demo Execution
Launch the App `ias_ios` in ios-simulator or on an ios-device and select `Start`. Perform another measurement by selecting `Load` followed by `Start`.
