[[ias-mobile-build]]
= IAS-mobile

.License
----
ias-mobile is released under the AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.txt>

Copyright (C) 2016-2020 zafaco GmbH

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License version 3 
as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
----

== Building

=== Prerequisites

* XCode >= 10
* cocoapods
* NativeScript = 5.x
* macOS (any Version)

Please Note: The `speed` framework of `ias-ios` uses the `TNSRuntime` (which is part of `nativescript`) provided by `ias-mobile`. NativeScript 7 defaults to the `v8 iOS engine`, which does not include `TNSRuntime`, and is therefore NOT compatible with `speed`. Hence, `tns-ios 6.5.3` must be used for the time being. Moreover, if compiled with xcode 12, the execution of JavaSript code within the `TNSRuntime` fails. Hence, xcode 11 must be used for the time being to compile the `speed` framework of `ias-ios`.

References:

https://nativescript.org/blog/nativescript-7-announcement/

https://github.com/NativeScript/NativeScript/issues/8867

https://github.com/NativeScript/NativeScript/issues/8741

=== Build

With fullfilled prerequisites perform the following steps:

1. Run `npm i` to install dependencies
2. Run `tns build ios`. If `tns build ios` fails, check if the following files have the executable bit set:

* `ias-mobile/platforms/ios/internal/nativescript-post-build`
* `ias-mobile/platforms/ios/internal/nativescript-pre-build`
* `ias-mobile/platforms/ios/internal/nativescript-pre-link`
* `ias-mobile/platforms/ios/internal/strip-dynamic-framework-architectures.sh`
* `ias-mobile/platforms/ios/internal/metadata-generator/bin/build-step-metadata-generator.py`
* `ias-mobile/platforms/ios/internal/metadata-generator/bin/objc-metadata-generator`

'''
