= Terms and Conditions
:toc: macro
:toc-title:
:encoding: utf-8
:lang: en

== [DRAFT]

//[[terms-of-use]]
== Terms of Use

BEREC offers users the opportunity to use the BEREC Nettest
software to test the quality and capacity of their current broadband
connection. Users use the browser version and apps of the BEREC
Nettest at their own risk. Please send any comments on correction of
inaccurate content, graphics etc. by e-mail to berec@berec.europa.eu.
Children under 16 years can use the BEREC Nettest with the consent
of their legal guardian.

BEREC Nettest provides users with transparent and detailed
information on the current quality of their broadband access service
while respecting their privacy. The test is based on open source and
open data principles. Open source principle means that the source code
of BEREC Nettest software is published. This is mainly for
transparency and reliability issues. Any commercial use of BEREC
Nettest source code, which is published under the MAME license, is not
allowed. The BEREC logo and used fonts are not subject to open
source and open data principles. Therefore copying, modifying or
processing them in changed or unchanged form is strictly prohibited.

BEREC Nettest measurement results data are retrievable as Open Data
and available for re-use under the "Creative Commons Namensnennung 3.0
Österreich" (CC BY 3.0) license. For that reason data are freely
available to the general public for information, use, dissemination and
other applications. Data which are not retrievable as Open Data are not
subject to the open data principle.

Links and references to other websites or persons outside BEREC are
provided to facilitate use and should not be deemed as approved by
BEREC. BEREC offers the service only to provide a greater and
easier public access to information. Where the website
(nntool.net-neutrality.tools) includes links to other websites, BEREC shall
not be deemed responsible for their content, copyright or privacy
policy, and shall not be held liable for any damage which the user incur
due or in connection to the use of the website, or use of any resources
or services offered by the relevant website, even if BEREC has been
informed on the possibility for such damage or should reasonably
anticipate such loss or damage.

There is no legal claim to permanent availability of the service.
BEREC explicitly reserves the right to change, add to or delete
parts of the BEREC Nettest or the entire BEREC Nettest service
without prior announcement, or to cease publication of it temporarily or
finally.

BEREC makes every endeavour to ensure the BEREC Nettest
browser version/website and BEREC Nettest apps are constantly
up-to-date, complete and accurate. To ensure the correctness of the
results, implausible measurements may be marked and/or removed by
BEREC. BEREC accepts no liability for
the up-to-dateness, correctness, completeness or quality of the
information and services provided. As a basic principle, no claims can
be brought against BEREC for material or immaterial disadvantages
and/or losses resulting from the use or non-use of information provided
or from the use of incorrect and incomplete information. Where
BEREC cannot assert a full waiver of liability due to the statutory
provisions applicable in the individual case, liability shall be limited
to gross negligence and malicious intent.

Test results acquired by BEREC Nettest are solely of informative
and illustrative purposes as there are too many technical parameters
undefined on the user side during the measurement process. Therefore test
results don’t represent any legal proof of broadband connection speed which
could lead to any consumer complaints cases.

All the data acquired through the BEREC Nettest system for
monitoring the quality of broadband service are solely of informative
and illustrative purposes and BEREC shall not be liable for any
conclusions or decisions of third parties with respect to the comparison
and ranking of network operators and service providers.


//[[privacy-policy]]
== Privacy Policy

BEREC respects the right to privacy and shall not collect any
personal data without the explicit consent of users. The personal data
which BEREC shall acquire on the basis of an explicit and informed
consent of users shall be processed by complying with the highest
security and confidentiality standards.

Prior to using BEREC Nettest users must acknowledge their explicit
acceptance of the Terms of Use and Privacy Policy of the BEREC
Nettest system for measuring the quality of broadband service. Without
this the BEREC Nettest cannot be performed. This acceptance can be
withdrawn at any time.

By accepting the general Terms of Use and Privacy Policy users
explicitly accept that BEREC (as the personal data administrator)
collects and processes personal data. +
Personal data are not collected for commercial purposes in any way.
BEREC shall not try to identify specific users, nor shall it link
the collected data therewith. The IP address and the Client UUID are
processed but not published, i.e. they are neither disclosed nor
published and are not retrievable as open data.

You can send all questions regarding the personal data protection and
privacy policy when using BEREC Nettest system for measuring the
quality of broadband service to the BEREC’s email address:
berec@berec.europa.eu.

The browser version of the BEREC Nettest uses cookies.
Cookies are little files sent from the server hosting the website to
your computer’s hard disk when you visit the BEREC Nettest website.
These cookies store the following sets of data: acceptance of the
privacy policy and terms of use, the randomly generated client ID
(client UUID) and the location (temporarily). These data are used to
identify users the next time they visit the BEREC Nettest website.

By accepting the Terms of Use and Privacy Policy the user also grants
explicit approval for the use and storage of cookies.

//[[the-purpose-of-personal-data-collection]]
=== The purpose of personal data collection

All data acquired by BEREC through the use of BEREC Nettest
and results of all measurements which are carried out by users are
recorded in a database. This database can only be accessed by the
employees of BEREC responsible for the management of the database.
Users and BEREC shall use the BEREC Nettest system to measure
the capacity and quality of network services provided by operators or
service providers. The system shall show where and with which ISPs there
are potential problems with access to internet services, where there is
no mobile or wireless signal and whether operators are acting net-neutral.

The user’s public IP address is being processed in order to determine
the network operator, to identify potential improper use of the system
and in order to prepare a history of measurements for a specific user.
The full IP address is recorded in the database, but shall not be
disclosed to public and can be viewed by the user itself only in the
mobile app under "Details" or in the browser under the "History" tab. +
WiFi SSID and BSSID is stored to help users to interpret their own
measurement results shown in "history". This is critical especially when
using different WiFi access points.

The selected and anonymised data from completed measurements (marked
with an asterisk) are published online and can be accessed through the
BEREC Nettest website, while allowing the interested public to gain
an independent and realistic insight in the state of mobile, wireless
and fixed communication systems and internet services. This provides
users with information on the network coverage for a specific network or
service provider at the level of regions, cities, districts or the most
common regular communication routes. Information on mobile coverage is
especially important for users, who travel on a daily basis, or users
without the possibilities to access fixed broadband networks.
