spring:
  profiles:
    active: dev

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false

logging:
  level:
    at.alladin.nettest: DEBUG
    org.springframework.web: TRACE

search-service:
  settings-uuid: "4e7567ef-175b-44f4-8436-8fd6d22dab48"
  elasticsearch:
    host: localhost
    port: 19200
    scheme: http
    index: nntool
    queryTimeout: 10s
