package at.alladin.nettest.shared.server.domain.model;

import com.fasterxml.jackson.annotation.JsonClassDescription;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * SubMeasurement class that is extended by specific measurements.
 * 
 * @author alladin-IT GmbH (bp@alladin.at)
 * @author alladin-IT GmbH (lb@alladin.at)
 * 
 */
@JsonClassDescription("SubMeasurement class that is extended by specific measurements.")
public class SubMeasurement {
	
	/**
	 * @see SubMeasurementTime
	 */
	@JsonPropertyDescription("This class extends the MeasurementTime class with relative time stamps.")
	@Expose
	@SerializedName("time")
	@JsonProperty("time")
	private SubMeasurementTime measurementTime;
	
	/**
	 * @see MeasurementStatusInfo
	 */
	@JsonPropertyDescription("Describes the status of a measurement.")
	@Expose
	@SerializedName("status_info")
	@JsonProperty("status_info")
	private MeasurementStatusInfo statusInfo;
	
	/**
	 * Flag to mark a measurement as implausible.
	 */
	@JsonPropertyDescription("Flag to mark a measurement as implausible.")
	@Expose
	@SerializedName("implausible")
	@JsonProperty("implausible")
	private boolean implausible;

	/**
	 * Measurement token generated by the collector.
	 */
	@JsonPropertyDescription("Measurement token generated by the collector.")
	@Expose
	@SerializedName("token")
	@JsonProperty("token")
	private String token;
	
	/**
	 * The protocol version this measurement used, if available.
	 */
	@JsonPropertyDescription("The protocol version this measurement used, if available.")
	@Expose
	@SerializedName("version_protocol")
	@JsonProperty("version_protocol")
	private String versionProtocol;
	
	/**
	 * The library version this measurement used, if available.
	 */
	@JsonPropertyDescription("The library version this measurement used, if available.")
	@Expose
	@SerializedName("version_library")
	@JsonProperty("version_library")
	private String versionLibrary;
}
