const replace = require('replace-in-file');
const results = replace.sync({
  	files: 'build/plain/core/Worker.js',
  	from: [
	  	/\nonmessage\s=\s/g,
		/function setWsParameters\(/g,
		/setWsParameters\(/g,
		/function connect\(\)/g,
		/connect\(\)/g,
		/function resetCounter\(\)/g,
		/resetCounter\(\)/g,
		/function websocketClose\(/g,
		/websocketClose\(/g,
		/function resetValues\(/g,
		/resetValues\(/g,
		/reportToControl\(/g,
		/roundTripTime\(\)/g,
		/download\(\)/g,
		/upload\(\)/g,
		/sendToWebSocket\(/g,
  	],
	to: [
  		'\nthis.onmessageWorker = ',
		'this.setWsParametersWorker = function(',
		'this.setWsParametersWorker(',
		'this.connectWorker = function()',
		'this.connectWorker()',
		'this.resetCounterWorker = function()',
		'this.resetCounterWorker()',
		'this.websocketCloseWorker = function(',
		'this.websocketCloseWorker(',
		'this.resetValuesWorker = function(',
		'this.resetValuesWorker(',
		'reportToControlWorker(',
		'roundTripTimeWorker()',
		'downloadWorker()',
		'uploadWorker()',
		'sendToWebSocketWorker('
	  ],
	  countMatches: true,
});