ENV['COCOAPODS_DISABLE_STATS'] = 'true'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

abstract_target 'All' do
  pod 'nntool-shared-swift', :path => '../nntool-shared-swift'

  pod 'Siesta', '~> 1.4.3'
  pod 'ReachabilitySwift', '~> 5.0.0'
  pod 'CocoaAsyncSocket', '~> 7.6.3'

  target 'MeasurementAgentKit_iOS' do
    platform :ios, '10.0'
  end

  target 'MeasurementAgentKitTests' do
      platform :ios, '10.0'

      pod 'Nimble', '~> 8.0.5'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['Siesta'].include? "#{target}"
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end

