ENV['COCOAPODS_DISABLE_STATS'] = 'true'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

abstract_target 'All' do
  pod 'SwiftLint', '~> 0.31.0'

  #pod 'Alamofire', '~> 4.8.1'
  pod 'Siesta', '~> 1.4.3'
  
  pod 'XCGLogger', '~> 6.1.0'

  pod 'QoSKit', :path => '../qos-client-swift'
  
  target 'MeasurementAgentKit_iOS' do
    platform :ios, '10.0'
  end

  target 'MeasurementAgentKitTests' do
      platform :ios, '10.0'
      
      pod 'Nimble', '~> 7.3.4'
  end
end

