ENV['COCOAPODS_DISABLE_STATS'] = 'true'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

abstract_target 'All' do
  pod 'nntool-shared-swift', :path => '../nntool-shared-swift'

  pod 'Siesta', '~> 1.5.0'
  pod 'ReachabilitySwift', '~> 5.0.0'
  pod 'CocoaAsyncSocket', '~> 7.6.4'

  target 'MeasurementAgentKit_iOS' do
    platform :ios, '10.0'
  end

  target 'MeasurementAgentKitTests' do
      platform :ios, '10.0'

      pod 'Nimble', '~> 8.0.7'
  end
end

