[[qos-server-documentation]]
= QoS Testserver Documentation

1.  <<qos-server-communication, Communication between server and client>>
2.  <<qos-server-protocol, QoS Testserver Protocol (= QTP)>>
3.  <<qos-server-settings, Settings>>
4.  <<qos-server-launching, Launching>>

[[qos-server-communication]]
== 1. Communication between server and client

=== 1.1 Overview

Each client is communicating with the test server by using a simple protocol. This protocol is called QoS Testserver Protocol (QTP) 
and consists of three parts. These parts have to be executed in the correct order. All parts are important and none must be omitted. They are:  

1.  establishing connection / handshake
2.  test request / test result
3.  close connection

The rules for the QTP are:

*   Each QTP command has to be in a single line
*   A new line character must follow the command string. This marks the end of the command.

[[qos-server-protocol]]
== 2. QoS Testserver Protocol (QTP)

=== 2.1 Handshake

A client tries to open a connection on the port the test server is listening on (see <<qos-server-settings, 3. Settings>>). 
If the connection can be established the server sends two lines of information: The first one is the greeting. 
This is the name and version number of the protocol this server uses. The second one is an **ACCEPT** command (see 2.4.1).  

After receiving these two lines of code the client needs to send back the identity token (by using the **TOKEN string** command). 
If the token is valid the server will send back an **OK** command followed by another **ACCEPT** command. The connection has been established.  

=== 2.2 Test requests

Tests are being requested by using a special test request command (see 2.4.2). The server's reaction is different for each test.
Every command sent by the client gets a response. The only exception is the **QUIT** command (see 2.3. Close connection) where a connection is closed immediately.

=== 2.3 Close connection

By using the **QUIT** command the client can close a connection.

=== 2.4 Command overview

All commands can have appendices with a special functionality. See 2.4.3  

==== 2.4.1 Server side responses

*   **ACCEPT [?]** - by sending this command the server is telling the client which commands it will accept for the next request. 
Example: _ACCEPT [TOKEN string]_ -> means that the server will only accept a _TOKEN_ command followed by a string (=this one is needed to complete the handshake and identify the client)
*   **OK** - each command that is received by the server, is valid and doesn't need a different reply from the server is confirmed with this command
*   **RCV ? ?** - this is used after an UDP test to tell the client how many packets have been received (first INTEGER) and how many of them have been duplicates (second INTEGER)
*   **ERR ?** - if an error occurs this message followed by the specific error is being returned. Possible errors are:
    **   **ERR ILLARG** - illegal argument. This is returned if an argument could be parsed but is illegal (out of range, etc.).
    **   **ERR UNSUPP** - argument unsupported. This is returned if an argument could be parsed but is not valid because it's not supported (old protocol version, etc.).

==== 2.4.2 Client side commands and possible responses

*   **TOKEN string** - sends a token (received from the control server) that is used to identify the client.  
    The response is: **OK** and an **ACCEPT** command
*   **UDPTEST IN int int** - sends an UDP incoming (server sends packets to client) test request. First parameter is the port number, the second one is the number of packets.
+
RETURNS: **nothing**  
As response UDP packets are sent to the client.

*   **UDPTEST OUT int int** - sends an UDP outgoing (servers receives packets) test request. First parameter is the port number (see _GET UDPPORT_), the second one is the number of packets.
+
RETURNS: **OK** test request successful
*   **GET UDPPORT** - request a random UDP port number the server is listening on.
+
RETURNS: **An integer value** that represents an available port number.
*   **TCPTEST IN int** - TCP incoming (server tries to establish a connection to client) test request. The only parameter is the port number.
+
RETURNS: **nothing**  
The response is a **HELLO TO port_number** message to the requested port_number.

*   **TCPTEST OUT int** - TCP outgoing (client tries to establish a connection to server) test request. The only parameter is the port number.  
    The response is an **OK** message after a server socket has been opened and is listening on the requested port.
+
RETURNS: **OK** - test request successful
*   **NTPTEST int** - Non transparent proxy test request. The only parameter is the port number.  
    The response is an **OK** message after a server socket has been opened and is listening on the requested port.
+
RETURNS: **OK** - test request successful
*   **GET UDPRESULT IN int** - Requests result for an incoming UDP test on a specific port. This can be requested any time by the client. The UDP test doesn't need to be finished.
+
RETURNS: **RCV int int** - see 2.4.1 RCV
*   **GET UDPRESULT OUT int** - Requests result for an outgoing UDP test on a specific port. This can be requested any time by the client. The UDP test doesn't need to be finished.
+
RETURNS: **RCV int int** - see 2.4.1 RCV
*   **QUIT** - closes the connection.
    There is no response to this command.

==== 2.4.3 Command appendices

An appendix can be added to each command for extended functionality. Each appendix is added after a command, 
but before the new-line character. An appendix must start with a plus (+) sign. Example: **TCPTEST OUT 80 +ID17**  
The following appendices are supported:

*   **ID** - If this appendix is added to a command the server will answer 
that command by adding the same appendix to the response. 
This is used for multi-threaded environments. 
The example from above **TCPTEST OUT 80 +ID17** would produce a response that will look like this: **OK +ID17**

[[qos-server-settings]]
== 3. Server Settings

The server settings can be set by using either predefined default values, command line parameters or a settings file.  

=== 3.1 Preset default values

If neither a configuration file is available nor the command line parameters are set then the default values are used. They are:

1.  _Configuration file:_ **config.properties**
2.  _Testserver IP:_ **all available interfaces** (see: _3.2.1 server.ip_)
3.  _Testserver port number:_ **5233** (see: _3.2.2 server.port_)
4.  _Supported UDP ports:_ **none** (see: _3.2.3, 3.2.4 'server.udp.*'_)
5.  _Max number of threads:_ **200** (see: _3.2.5 server.threads_)
6.  _Secret key:_ **there is no default secret key. This setting is required** (see: _3.2.6 server.secret_)
7.  _Verbose level:_ **the verbose (debug output) level: either 0 (=some debug), 1 (=more debug) or 2 (=most debug)** (see: _3.2.7 server.verbose_)
8.  _Secure flag:_ **tells the server to use SSL Sockets** (see: _3.2.8 server.ssl_)
9.  _Log files:_ **none** (see: _3.2.10 'server.log.*'_)
10.  _Command console:_ **disabled** (see: _3.2.11 'server.console'_)
11.  _Log console:_ **disabled** (see: _3.2.11 'server.log.console'_)

=== 3.2 Settings file

If a settings file is available the parameters set inside have the highest priority. 
The following parameters are available inside a configuration file:

1.  **server.ip** _Testserver IPs:_ binds the server to these IPs. Multiple IPs can be separated by a comma.
 The test server accepts both: IPv4 and IPv6.
2.  **server.port** _Testserver port number_
3.  **server.udp.minport** and **server.udp.maxport** (_both Deprecated_) _Supported UDP port range_: 
All UDP ports inside this range (inclusive boundaries) will be opened for incoming UDP tests.
4.  **server.udp.ports** _Supported UPD port list:_ multiple ports can be separated by a comma,
 e.g.: **22,443,4551,23435**: All ports on this list will be opened for incoming UDP tests.
5.  **server.threads** _Max number of threads (=max number of control connections)_
6.  **server.secret** _Secret key_
7.  **server.verbose** _Verbose level:_ values: **0/1/2**
8.  **server.ssl** _SSL settings:_ values: **true/false**
9.  **server.ip.check** (_Deprecated_) _Client IP check:_ values: **true/false**. Checks the IP of TCP test candidates. 
If set to true a candidate map will be managed by the server, where only allowed client IPs 
(received during the test registration process) will get responses from the qos server.
10.  _Log files. The file names should contain the full path including a prefix (e.g.: **/var/log/main**). 
An automatically generated suffix is added to the name (date + ".log" ending)_
    *   **server.log** main QoS server log file
    *   **server.log.udp** log file for all UDP operations
    *   **server.log.tcp** log file for all TCP operations
11.  Other log settings:
    *   **server.log.console** values: **true/false**, if true, all debug messages will be sent to the available console

=== 3.3 Command line parameter

By launching the test server the following command line parameters can be used.
However, configuration via the settings file is the preferred method, because of its extended functionality:

1.  _Configuration file:_ **-f [file_name]**
2.  _Testserver port number:_ **-p [port_number]**
3.  _Supported UDP port range:_ **-u [port_from] [port_to]**
4.  _Max number of threads:_ **-t [num_of_threads]**
5.  _Secret key:_ **-k [secret_key]**
6.  _Show help:_ **-h**
7.  _Verbose:_ **-v** (= verbose level 1) or **-vv** (= verbose level 2), 
if this parameter is not set to verbose, it is set to level 0 automatically.
8.  _Secure flag:_ **-s**
9.  _Main log file (for more log files use a config file - see 3.4):_ **-l**

[[qos-server-launching]]
== 4. Launching

After building the qos-service (use ``./gradlew build``), move to the directory containing the jar (``qos-service-1.0.jar``)
and execute ``java -jar qos-service-1.0.jar`` to start the server.
