== IAS libnntool module

=== Building

==== Prerequisites

Linux (any Version)

- ninja
- cmake
- g++
- liblog4cpp5-dev
- libssl-dev
- golang
- lcov

For a Debian based Linux run the following command as root:

[source,bash]
----
apt install build-essential ninja cmake g++ liblog4cpp5-dev libssl-dev golang lcov
----

==== Build

With fullfilled prerequisites perform the following steps:

[source,bash]
----
cd <nntool_eu_directory>/ias-libnntool
mkdir build
cd build
cmake .. -GNinja # add -DCMAKE_BUILD_TYPE="DEBUG" for debug build
ninja
----

==== Unit Tests

To execute the included unit tests execute the following commands:

[source,bash]
----
cd <nntool_eu_directory>/ias-libnntool
mkdir build
cd build
cmake .. -GNinja -DCMAKE_BUILD_TYPE="DEBUG"
ninja
./nntool_test
----

To generate the code coverage reports run the following commands after running the unit tests:

[source,bash]
----
lcov --capture --directory . --output-file coverage.info
lcov --remove coverage.info '/usr/*' --output-file coverage.info
lcov --remove coverage.info '*external/*' --output-file coverage.info
genhtml coverage.info --branch-coverage --output-directory ./coverage_report/
lcov --list coverage.info
----

The HTML code coverage report will be generated into directory `ias-libnntool/build/coverage_report`.

=== License

ias-libnntool is released under the AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.txt>

Copyright (C) 2016-2019 zafaco GmbH

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License version 3 
as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.