# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  application:
    name: result-service

  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false

server:
  port: 8087

# ===================================================================
# Result service specific properties
# ===================================================================

loadbalancer:
  enabled: false
  default: 10000