spring:
  application:
    name: statistic-service
    
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false

server:
  port: 8085

  #messages:
  #  basename: i18n/messages

data-export:
  cache-threshold-sec: 60
  compress: false
  suffix: FROM measurements m LEFT JOIN network_types n ON m.initial_network_type_id = n.id LEFT JOIN speed_measurements sm ON m.open_data_uuid = sm.measurement_open_data_uuid
  where-clause: status = 'FINISHED'

  where-open-test-uuid-clause: AND open_data_uuid = ?::uuid
  where-day-clause: AND (EXTRACT (day FROM m.start_time AT TIME ZONE 'UTC') = ?
  where-month-clause: AND (EXTRACT (month FROM m.start_time AT TIME ZONE 'UTC') = ?
  where-year-clause: AND (EXTRACT (year FROM m.start_time AT TIME ZONE 'UTC') = ?

  order-by: m.start_time
  fields:
    open_test_uuid: ('O' || (open_data_uuid)::text)
    system_uuid: m.system_uuid
    time_utc: to_char(m.start_time AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
    cat_technology: network_group_name
    network_type: n.name
    lat: geo_location_latitude
    long: geo_location_longitude
    loc_accuracy: geo_location_accuracy
    download_kbit: throughput_avg_download_bps / 1000
    upload_kbit: throughput_avg_upload_bps / 1000
    ping_ms: rtt_median_ns / 1000000
    lte_rsrp: mobile_network_lte_rsrp_dbm
    test_duration: m.duration_ns
    platform: m.os_name
    model: COALESCE(m.device_fullname, m.device_model)
    client_version: m.agent_app_version_code
    network_mcc_mnc: mobile_network_operator_mcc || '-' || mobile_network_operator_mnc
    network_name: mobile_network_operator_name
    sim_mcc_mnc: mobile_sim_operator_mcc || '-' || mobile_sim_operator_mnc
    asn: provider_public_ip_asn
    ip_anonym: network_client_public_ip
    implausible: implausible
    signal_strength: mobile_network_signal_strength_2g3g_dbm
