spring:
  application:
    name: statistic-service
    
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false

server:
  port: 8083

# ===================================================================
# Statistic service specific properties
# ===================================================================

statistic-service:
