ENV['COCOAPODS_DISABLE_STATS'] = 'true'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

abstract_target 'All' do
  pod 'SwiftLint', '~> 0.39.2'

  pod 'CodableJSON', '~> 1.2.0'
  pod 'XCGLogger', '~> 7.0.1'
  pod 'Repeat', '~> 0.5.8'

  target 'nntool-shared-swift' do
    platform :ios, '10.0'
  end

  target 'nntool-shared-swiftTests' do
      platform :ios, '10.0'

      pod 'Nimble', '~> 8.0.7'
  end
end

