== Authentication

The measurement peers running ias-server allow the authentication of measurement requests. To enable authentication, provide the requested configuration within the `authentication` object in `config.json` of ias-server.

The following options are available:

[cols="4,2,4,10",options=header]
|===
|Option
|Type
|Default
|Desciption
|`enabled`
|boolean
|`false`
|Enables (`true`) or disables (`false`) authentication
|`secret`
|string
|`my_auth_secret`
|The shared secret between measurement peer and controller
|`max_age`
|int
|`120`
|The maximum validity of an authentication in seconds
|===

If authentication is deactivated, the services provided by ias-server (rtt, download, upload, traceroute) can be used without a valid authentication, and therefore without registering with the controller. If authentication is activated, the services can only be used with a valid authentication. The required values are provided by the controller during measurement registration using the following scheme:
----
auth_timestamp = current UTC timestamp of the controller in us
auth_token = sha1(auth_timestamp + shared_secret)
----
The measurement agent forwards the parameters according to the respective APIs to the `ias*` modules. Upon request, `ias-server` tries to validate the provided authentication parameters, while computing `sha1(auth_timestamp + shared_secret)` and comparing it with the provided `auth_token`. If the computed and the provided `auth_token` match, the maximum validity is checked using the `max_age` parameter as defined in `config.json`. To account for different timezone offsets, `auth_timestamp` must always be stated as a UTC Timestamp. If all steps are completed successful, the measurement continues. If the authentication is unsuccessful, an error is thrown and the connection is dropped.