# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  application:
    name: collector-service

#  messages:
#    basename: classpath:/i18n/messages
    #cache-seconds: ...
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false

server:
  port: 8081

#springfox:
#  documentation:
#    swagger:
#      v2:
#        path: /api/v1-documentation

# ===================================================================
# Collector service specific properties
# ===================================================================

collector:
